#!/usr/bin/env bun
/**
 * Scans packages/templates/<skill>/ and emits
 * packages/cli/src/generated/template-manifest.ts
 * with explicit static imports. Run via `bun run gen:manifest`
 * (auto-fires on prebuild).
 */
import { mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const CLI_ROOT = join(import.meta.dir, "..");
const REPO_ROOT = join(CLI_ROOT, "../..");
const TEMPLATES_DIR = join(REPO_ROOT, "packages/templates");
const OUT_PATH = join(CLI_ROOT, "src/generated/template-manifest.ts");
const SHARED_FILES = new Set(["LICENSE"]);

// Top-level dirs under packages/templates/ that act as author namespaces — codegen
// descends one level so that templates/<author>/<skill>/ is treated as a skill at
// the manifest tree's <skill> key (with the author folded into the import path only).
// Add new authors here as upstream sources land.
const AUTHOR_NAMESPACES = new Set<string>(["patterns-dev"]);

interface ManifestEntry {
  importName: string;
  importPath: string;
  skill: string;
  tool: string;
  key: string;
}

function sortedReaddir(dir: string): import("node:fs").Dirent[] {
  // Sort deterministically so codegen output is stable across filesystems
  // (APFS, ext4, tmpfs all differ in native readdirSync order).
  return readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name));
}

function walkMd(dir: string, base: string, entries: string[] = []): string[] {
  for (const dirent of sortedReaddir(dir)) {
    const full = join(dir, dirent.name);
    if (dirent.isDirectory()) walkMd(full, base, entries);
    else if (/\.md$/.test(dirent.name)) entries.push(relative(base, full));
  }
  return entries;
}

function sanitizeIdent(s: string): string {
  return s.replace(/[^a-zA-Z0-9]/g, "_");
}

function collect(): ManifestEntry[] {
  const entries: ManifestEntry[] = [];
  for (const top of sortedReaddir(TEMPLATES_DIR)) {
    if (!top.isDirectory()) continue;
    const topDir = join(TEMPLATES_DIR, top.name);

    if (AUTHOR_NAMESPACES.has(top.name)) {
      // Author tier: walk children as skills, prefix import path with author/
      for (const skill of sortedReaddir(topDir)) {
        if (!skill.isDirectory()) continue;
        collectSkill(entries, join(topDir, skill.name), skill.name, `${top.name}/${skill.name}`);
      }
    } else {
      // Direct skill tier: existing 2-level layout
      collectSkill(entries, topDir, top.name, top.name);
    }
  }
  return entries;
}

function collectSkill(
  entries: ManifestEntry[],
  skillDir: string,
  skillKey: string,
  importPrefix: string,
): void {
  for (const item of sortedReaddir(skillDir)) {
    if (item.isFile() && SHARED_FILES.has(item.name)) {
      entries.push({
        importName: `${sanitizeIdent(skillKey)}__shared__${sanitizeIdent(item.name)}`,
        importPath: `@au-agentic/templates/${importPrefix}/${item.name}`,
        skill: skillKey,
        tool: "_shared",
        key: item.name,
      });
    } else if (item.isFile() && !SHARED_FILES.has(item.name) && /\.md$/.test(item.name)) {
      entries.push({
        importName: `${sanitizeIdent(skillKey)}__copilot__${sanitizeIdent(item.name)}`,
        importPath: `@au-agentic/templates/${importPrefix}/${item.name}`,
        skill: skillKey,
        tool: "copilot",
        key: item.name,
      });
    } else if (item.isDirectory()) {
      const toolDir = join(skillDir, item.name);
      for (const rel of walkMd(toolDir, toolDir)) {
        entries.push({
          importName: `${sanitizeIdent(skillKey)}__${sanitizeIdent(item.name)}__${sanitizeIdent(rel)}`,
          importPath: `@au-agentic/templates/${importPrefix}/${item.name}/${rel}`,
          skill: skillKey,
          tool: item.name,
          key: rel,
        });
      }
    }
  }
}

function render(entries: ManifestEntry[]): string {
  const imports = entries
    .map((e) => `import ${e.importName} from "${e.importPath}" with { type: "text" };`)
    .join("\n");

  const byShape: Record<string, Record<string, Record<string, string>>> = {};
  for (const e of entries) {
    let tools = byShape[e.skill];
    if (tools === undefined) {
      tools = {};
      byShape[e.skill] = tools;
    }
    let files = tools[e.tool];
    if (files === undefined) {
      files = {};
      tools[e.tool] = files;
    }
    files[e.key] = e.importName;
  }

  const manifestLines = Object.entries(byShape)
    .map(([skill, tools]) => {
      const toolLines = Object.entries(tools)
        .map(([tool, files]) => {
          const fileLines = Object.entries(files)
            .map(([k, name]) => `    ${JSON.stringify(k)}: ${name},`)
            .join("\n");
          return `  ${JSON.stringify(tool)}: {\n${fileLines}\n  },`;
        })
        .join("\n");
      return `  ${JSON.stringify(skill)}: {\n${toolLines}\n  },`;
    })
    .join("\n");

  return `// AUTO-GENERATED by packages/cli/scripts/generate-template-manifest.ts
// DO NOT EDIT. Run \`bun run gen:manifest\` (or \`bun run build\`) to regenerate.

${imports}

export const TEMPLATE_MANIFEST = {
${manifestLines}
} as const;

export type TemplateManifest = typeof TEMPLATE_MANIFEST;
`;
}

function main(): void {
  const entries = collect();
  if (entries.length === 0) throw new Error("No template entries found");
  mkdirSync(join(OUT_PATH, ".."), { recursive: true });
  writeFileSync(OUT_PATH, render(entries));
  console.log(`✓ Wrote ${entries.length} entries to ${relative(REPO_ROOT, OUT_PATH)}`);
}

if (import.meta.main) main();
